[theme]

# Primary accent for interactive elements
primaryColor = '#a4e356'

# Background color for the main content area
backgroundColor = '#f1faea'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#7fa349'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
