[theme]

# Primary accent for interactive elements
primaryColor = '#83b545'

# Background color for the main content area
backgroundColor = '#f1faea'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#546e2f'

# Color used for almost all text
textColor = '#0d0d0c'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
